# Generated by Django 2.0.6 on 2018-06-28 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('question_num', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_path', models.CharField(max_length=200)),
                ('store_name', models.CharField(max_length=200)),
                ('store_id', models.AutoField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key='True', serialize=False)),
                ('user_passwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netdisk2.User'),
        ),
        migrations.AddField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netdisk2.User'),
        ),
    ]
