# Generated by Django 2.0.6 on 2018-06-28 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netdisk2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_path2',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='netdisk2.User'),
        ),
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='netdisk2.User'),
        ),
    ]
