# Generated by Django 2.0.6 on 2018-06-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netdisk2', '0002_auto_20180628_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
    ]
