# Generated by Django 2.0.6 on 2018-06-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netdisk2', '0003_remove_store_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfile', models.FileField(upload_to='')),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
