# Generated by Django 2.0.6 on 2018-08-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netdisk2', '0007_auto_20180817_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='file_path',
            field=models.CharField(default='path', max_length=100),
        ),
    ]
