# Generated by Django 2.0.6 on 2018-08-21 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netdisk2', '0008_filemodel_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=50, primary_key='True', serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(default='no description', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.RenameField(
            model_name='filemodel',
            old_name='myfile',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='filemodel',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_passwd',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file_description',
            field=models.CharField(default='no description', max_length=100),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='owner_analysis',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netdisk2.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='admin', max_length=40),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netdisk2.User'),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='netdisk2.Group'),
        ),
    ]
