# Generated by Django 2.0.6 on 2018-08-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netdisk2', '0009_auto_20180821_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='filemodel',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
