# Generated by Django 2.0.6 on 2018-08-24 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netdisk2', '0010_auto_20180821_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrouptoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netdisk2.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netdisk2.User')),
            ],
        ),
    ]
