# Generated by Django 2.0.6 on 2018-08-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netdisk2', '0011_grouptouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='name',
            field=models.CharField(blank=True, default='default', max_length=60, null=True),
        ),
    ]
